###############################################################################
# transparenciabr — Sprint 2 Orchestrator Variables
###############################################################################

variable "project_id" {
  description = "Google Cloud project ID where all resources will be created."
  type        = string
}

variable "region" {
  description = "Google Cloud region for all regional resources (Cloud Run, Pub/Sub, Functions, Scheduler)."
  type        = string
  default     = "us-west1"
}

variable "arsenal_bucket" {
  description = "GCS bucket name that holds the API catalog (config/arsenal_apis.json), contracts, and function source archives."
  type        = string
}

variable "datalake_bucket" {
  description = "GCS bucket name for the raw data lake output (DATALAKE_BUCKET_RAW). All ingested NDJSON.gz files and manifests land here."
  type        = string
}

variable "lgpd_salt_secret_name" {
  description = "Full Secret Manager secret resource name for the LGPD SHA-256 salt, e.g. projects/PROJECT_ID/secrets/lgpd-salt. Must include /versions/latest or an explicit version."
  type        = string
  default     = ""
}

variable "vertex_reasoning_engine_id" {
  description = "Full Vertex AI Reasoning Engine resource name for the Líder Supremo deploy (Agent Builder agent_1777236402725). Passed to Cloud Run as VERTEX_REASONING_ENGINE_ID. When empty, Terraform builds projects/{project_id}/locations/{region}/reasoningEngines/{numeric_id}."
  type        = string
  default     = ""
}

variable "vertex_reasoning_engine_numeric_id" {
  description = "Numeric Reasoning Engine ID segment (same deployment as Líder Supremo agent_1777236402725). Used only when vertex_reasoning_engine_id is empty. Set explicitly in tfvars — no default in repo (SecOps)."
  type        = string
  default     = ""
}

variable "orchestrator_source_zip" {
  description = "Local path to the Cloud Function source ZIP archive (orchestrator_trigger/). Example: ../../dist/orchestrator-trigger.zip. Generated by CI before terraform apply."
  type        = string
  default     = "../../dist/orchestrator-trigger.zip"
}

variable "image_tag" {
  description = "Docker image tag for the agent_worker Cloud Run service. Defaults to 'latest' — CI should pin this to a git SHA for reproducibility."
  type        = string
  default     = "latest"
}

variable "bq_daily_budget_bytes" {
  description = "Maximum BigQuery bytes billed per day across all agent workers. Passed as BQ_DAILY_BUDGET_BYTES env var. Default: 107374182400 (100 GB)."
  type        = number
  default     = 107374182400
}

variable "openlineage_url" {
  description = "HTTP(S) endpoint to receive OpenLineage events. Leave empty to emit events to Cloud Logging stdout only."
  type        = string
  default     = ""
}

variable "cloud_run_max_instances" {
  description = "Maximum number of Cloud Run instances for the agent_worker service. Must not exceed 12 (number of Pub/Sub subscriptions)."
  type        = number
  default     = 12

  validation {
    condition     = var.cloud_run_max_instances >= 1 && var.cloud_run_max_instances <= 12
    error_message = "cloud_run_max_instances must be between 1 and 12."
  }
}

variable "pubsub_dlq_retention_days" {
  description = "Number of days to retain messages in the dead-letter topic."
  type        = number
  default     = 7

  validation {
    condition     = var.pubsub_dlq_retention_days >= 1 && var.pubsub_dlq_retention_days <= 31
    error_message = "pubsub_dlq_retention_days must be between 1 and 31."
  }
}

variable "scheduler_cron" {
  description = "Cloud Scheduler cron expression for the daily imediata run. Default: '0 5 * * *' (05:00 UTC = 02:00 Brasília)."
  type        = string
  default     = "0 5 * * *"
}

variable "labels" {
  description = "Additional labels to apply to all resources (merged with module-level labels)."
  type        = map(string)
  default     = {}
}
