substitutions:
  _REGION: us-central1
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/transparenciabr/ingest-universal:$SHORT_SHA'
      - .
    dir: engines
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/transparenciabr/ingest-universal:$SHORT_SHA'
