/**
 * Seis frentes de auditoria — mesma semântica na landing e no Universo (âncoras → /dashboard#…).
 */
export const INVESTIGATION_CATEGORIES = [
  {
    seed: "asmodeus.ceap",
    score: 90,
    label: "Cota CEAP",
    headline: "R$ 4 bi/ano",
    body: "Cada nota é suspeita até prova contrária. Locação, combustível, divulgação parlamentar — auditados nota a nota.",
    to: "/ranking?modulo=ceap",
    dashboardHash: "ceap",
    cta: "Investigar gastos",
  },
  {
    seed: "asmodeus.patrimonio",
    score: 78,
    label: "Patrimônio TSE",
    headline: "+1.200%",
    body: "Crescimento patrimonial entre eleições. Bens declarados vs. faixa salarial — outliers expostos.",
    to: "/ranking?modulo=patrimonio",
    dashboardHash: "patrimonio",
    cta: "Ver enriquecimento",
  },
  {
    seed: "asmodeus.gabinete",
    score: 72,
    label: "Folha do Gabinete",
    headline: "21 secretários",
    body: "Familiares, sócios e fantasmas no gabinete. Cruzamento CPF × empresa × parentesco.",
    to: "/ranking?modulo=folha",
    dashboardHash: "folha",
    cta: "Mapear gabinete",
  },
  {
    seed: "asmodeus.viagens",
    score: 65,
    label: "Viagens & Pedágios",
    headline: "48 passagens",
    body: "Carro alugado em Brasília, pedágio no Rio. SEM PARAR não mente — geolocalização forense.",
    to: "/ranking?modulo=viagens",
    dashboardHash: "viagens",
    cta: "Rastrear deslocamento",
  },
  {
    seed: "asmodeus.emendas",
    score: 82,
    label: "Emendas & PIX",
    headline: "R$ 50 bi",
    body: "Emendas relator, individuais e PIX. Beneficiários terminais, ONGs sem CNAE, prefeituras-fachada.",
    to: "/ranking?modulo=emendas",
    dashboardHash: "emendas",
    cta: "Seguir o dinheiro",
  },
  {
    seed: "asmodeus.contratos",
    score: 60,
    label: "Contratos PNCP",
    headline: "3,7 mi licitações",
    body: "Vencedores recorrentes, sobrepreço, dispensa indevida. OCR + Gemini sob direito administrativo.",
    to: "/ranking?modulo=contratos",
    dashboardHash: "contratos",
    cta: "Auditar licitações",
  },
];
